# Generated by Django 4.0.4 on 2022-05-16 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='category name')),
                ('description', models.CharField(max_length=200, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'Expense Category',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='category name')),
                ('description', models.CharField(max_length=200, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'Income Category',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='income amount')),
                ('date', models.DateField(verbose_name='income date')),
            ],
            options={
                'verbose_name': 'Query Information',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25, verbose_name='first name')),
                ('middleName', models.CharField(max_length=25, verbose_name='middle name')),
                ('lastName', models.CharField(max_length=25, verbose_name='last name')),
                ('email', models.CharField(max_length=30, verbose_name='e-mail address')),
                ('phone', models.CharField(max_length=10, verbose_name='phone number')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='account balance')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='IncomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='income amount')),
                ('date', models.DateField(verbose_name='income date')),
                ('description', models.CharField(max_length=50, verbose_name='income description')),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='balance.incomecategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.userinfo')),
            ],
            options={
                'verbose_name': 'Income Information',
            },
        ),
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='expense amount')),
                ('date', models.DateField(verbose_name='expense date')),
                ('description', models.CharField(max_length=50, verbose_name='expense description')),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='balance.expensecategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.userinfo')),
            ],
            options={
                'verbose_name': 'Expense Information',
            },
        ),
    ]
